export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    borderRadius: {
      none: '0px',
      sm: '2px',
      DEFAULT: '4px',
      md: '4px',
      lg: '6px',
      full: '9999px',
    },
    fontSize: {
      xs: ['12px', { lineHeight: '1.4' }],
      sm: ['14px', { lineHeight: '1.55' }],
    },
    extend: {
      colors: {
        og: {
          25: '#f1f2f4',
          50: '#e3e4e7',
          100: '#ced1d6',
          200: '#c0c3ca',
          300: '#abafb8',
          400: '#878e9b',
          500: '#6d7484',
          600: '#626976',
          700: '#535964',
          800: '#474c55',
          900: '#35383f',
          1000: '#0d0d0f',
        },
        accent: {
          DEFAULT: '#1348dc',
          hover: '#0f3bb8',
          soft: '#eaf0ff',
        },
        page: '#fafafa',
        surface: '#ffffff',
        hairline: '#e8e9ec',
        term: '#fdfdfd',
        'diff-add': '#e6f4ec',
        'diff-del': '#fdecea',
        'diff-add-ink': '#15803d',
        'diff-del-ink': '#b91c1c',
      },
      fontFamily: {
        sans: [
          '"iA Writer Quattro S"',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
        display: [
          '"Lilex"',
          '"iA Writer Quattro S"',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      boxShadow: {
        modal: '0 12px 32px rgba(15, 23, 42, 0.12)',
        toast: '0 4px 12px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [],
};
