export const blank = (n: number): string[] => Array(n).fill('');

export const CC_NONYOLO_IDLE = [
  " ▎ Run /model and select Fable to use it. Learn more",
  ...blank(27),
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯\u00a0",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  wd-cc Fable 5",
  "  ⏸ manual mode on · ← for agents",
].join('\n');

export const CODEX_NONYOLO_IDLE = [
  "│                                                          │",
  "│ model:     gpt-5.5 xhigh   /model to change              │",
  "│ directory: /private/tmp/claude-501/…/yolo-probe/wd-codex │",
  "╰──────────────────────────────────────────────────────────╯",
  "",
  "  Tip: New Use /fast to enable our fastest inference with increased plan usage.",
  "",
  "• You have 2 usage limit resets available. Run /usage to use one.",
  "",
  "",
  "› Run /review on my current changes",
  "",
  "  gpt-5.5 xhigh · /private/tmp/claude-501/-Users-devuser--baxian-repos-example-baxian/f2fbbf50-44f3-4478-b9b7-2f1da4c55fad/scratchpad/yolo-probe/wd-codex",
  ...blank(35),
].join('\n');

export const OC_NONYOLO_FRESH_IDLE = [
  "                                                                                 ▀▀▀▀ █▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀",
  "",
  "",
  "                                                               ┃",
  "                                                               ┃  Ask anything... \"What is the tech stack of this project?\"",
  "                                                               ┃",
  "                                                               ┃  Build · GLM-5.2 Alibaba (China) · max",
  "                                                               ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "                                                                                                               tab agents  ctrl+p commands",
  ...blank(18),
  "  /private/tmp/claude-501/-Users-devuser--baxian-repos-example-baxian/f2fbbf50-44f3-4478-b9b7-2f1da4c55fad/scratchpad/yolo-probe/wd-oc                                                         1.17.16",
  "",
].join('\n');

export const OC_YOLO_FRESH_IDLE = [
  "                                                                                 ▀▀▀▀ █▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀",
  "",
  "",
  "                                                               ┃",
  "                                                               ┃  Ask anything... \"What is the tech stack of this project?\"",
  "                                                               ┃",
  "                                                               ┃  Build auto · GLM-5.2 Alibaba (China) · max",
  "                                                               ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "                                                                                                               tab agents  ctrl+p commands",
  ...blank(18),
  "  /private/tmp/claude-501/-Users-devuser--baxian-repos-example-baxian/f2fbbf50-44f3-4478-b9b7-2f1da4c55fad/scratchpad/yolo-probe/wd-oc2                                                        1.17.17",
  "",
].join('\n');

export const QODER_NONYOLO_FRESH_IDLE = [
  " ██      ██                            │ 1. Create AGENTS.md files to customize interactions          │",
  " ██  ██  ██  Qoder CLI v1.0.41         │ 2. /help for more information                                │",
  " ██    ██                              │ 3. Ask coding questions, edit code or run commands           │",
  "   ████  ██  Signed in Browser Login   │ 4. Be specific for the best results                          │",
  "                                       ╰──────────────────────────────────────────────────────────────╯",
  "",
  "",
  "                                                                                                                                                                                        ? for shortcuts",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " Shift+Tab to Accept Edits                                                                                                                                                  Try /model to switch models",
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
  " >   Type your message or @path/to/file",
  "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  " GLM-5.2 (Alibaba Cloud Model Studio - China) Model · ctx ░░░░░░░░░░ 0%",
  ...blank(34),
].join('\n');

export const QODER_YOLO_FRESH_IDLE = [
  " ██      ██                            │ 1. Create AGENTS.md files to customize interactions          │",
  " ██  ██  ██  Qoder CLI v1.0.41         │ 2. /help for more information                                │",
  " ██    ██                              │ 3. Ask coding questions, edit code or run commands           │",
  "   ████  ██  Signed in Browser Login   │ 4. Be specific for the best results                          │",
  "                                       ╰──────────────────────────────────────────────────────────────╯",
  "",
  "",
  "                                                                                                                                                                                        ? for shortcuts",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " YOLO Shift+Tab to Auto Mode                                                                                                                                                Try /model to switch models",
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
  " *   Type your message or @path/to/file",
  "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  " GLM-5.2 (Alibaba Cloud Model Studio - China) Model · ctx ░░░░░░░░░░ 0%",
  ...blank(34),
].join('\n');

export const CC_NONYOLO_BASH_PERMISSION_LINES = [
  "⏺ bx475",
  "",
  "✻ Churned for 10s",
  "",
  "❯ Run this exact bash command: touch /tmp/bx475-perm-probe",
  "",
  "⏺ Running 1 shell command…",
  "  ⎿  $ touch /tmp/bx475-perm-probe",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " Bash command",
  "",
  "   touch /tmp/bx475-perm-probe",
  "   Create empty file /tmp/bx475-perm-probe",
  "",
  " Do you want to proceed?",
  " ❯ 1. Yes",
  "   2. Yes, and always allow access to tmp/ from this project",
  "   3. No",
  "",
  " Esc to cancel · Tab to amend · ctrl+e to explain",
];

export const CC_NONYOLO_BASH_PERMISSION = [...CC_NONYOLO_BASH_PERMISSION_LINES, ...blank(6)].join('\n');

export const CODEX_NONYOLO_ESCALATION_LINES = [
  "• Done.",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "",
  "",
  "› Run this exact bash command: touch ~/bx475-perm-probe",
  "",
  "",
  "• Running touch ~/bx475-perm-probe",
  "",
  "",
  "  Would you like to run the following command?",
  "",
  "  Environment: local",
  "",
  "  Reason: Do you want to allow creating /Users/devuser/bx475-perm-probe in your home directory?",
  "",
  "  $ touch ~/bx475-perm-probe",
  "",
  "› 1. Yes, proceed (y)",
  "  2. Yes, and don't ask again for commands that start with `touch '~/bx475-perm-probe'` (p)",
  "  3. No, and tell Codex what to do differently (esc)",
  "",
  "  Press enter to confirm or esc to cancel",
];

export const CODEX_NONYOLO_ESCALATION = [...CODEX_NONYOLO_ESCALATION_LINES].join('\n');

export const OC_NONYOLO_EXTERNAL_DIR_PERMISSION = [
  "  ┃",
  "  ┃  Run this exact bash command: touch /tmp/bx475-perm-probe",
  "  ┃",
  "",
  "     $ touch /tmp/bx475-perm-probe",
  "",
  "     ▣  Build · GLM-5.2",
  ...blank(14),
  "  ┃",
  "  ┃  △ Permission required",
  "  ┃    ← Access external directory /tmp",
  "  ┃",
  "  ┃  Patterns",
  "  ┃                                                                                                                                                             /private/tmp/claude-501/-Users-",
  "  ┃  - /tmp/*                                                                                                                                                   devuser--baxian-repos-example-baxian/",
  "  ┃                                                                                                                                                             f2fbbf50-44f3-4478-b9b7-2f1da4c55fad/",
  "  ┃                                                                                                                                                             scratchpad/yolo-probe/wd-oc",
  "  ┃   Allow once   Allow always   Reject                                                                       ctrl+f fullscreen  ⇆ select  enter confirm",
  "  ┃                                                                                                                                                             • OpenCode 1.17.16",
  "",
].join('\n');

export const QODER_NONYOLO_SHELL_PERMISSION_LINES = [
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
  " > Run this exact bash command: echo bx475",
  "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "",
  " Thinking",
  " │ The user wants me to run a specific bash command.",
  " ? Bash(echo bx475)",
  "",
  " Permission Required",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " Tool: Bash",
  "",
  " Print bx475",
  " Command: echo bx475",
  "",
  " Allow this command to run?",
  "",
  "  ❯ 1. Allow once",
  "    2. Always allow \"echo\" for future sessions [local]",
  "    3. Reject and type something",
  "    4. No",
];

export const QODER_NONYOLO_SHELL_PERMISSION = [...QODER_NONYOLO_SHELL_PERMISSION_LINES, ...blank(20)].join('\n');
